### ISSUE TITLE
Doesn't support high DPI correctly so messages difficult to view

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/DeviceLens#10]
The messages view is squashed up because it isn't taking into account the High DPI settings of the screen.
For info, the application is running under Parallels Desktop on an M1 Retina display Mac (3600x2252 @ 350% scale)

<img width="1345" alt="Screenshot 2022-12-20 at 17 04 18" src="https://user-images.githubusercontent.com/37405280/208724281-60bbd2dc-4c97-4af8-b4b1-e269e526d662.png">

**Comment by DelphiWorlds** [comment]
Device Lens uses [this fork of NiceGrid](https://github.com/DelphiWorlds/NiceGrid). Any help in making it work in high DPI would be welcome :-)

**Comment by MyBuzzTechnologies** [comment]
No problem, I'll take a look as soon as I get chance

**Comment by DelphiWorlds** [comment]
This is beta 2 of v2.0.0 (just the executable) - should fix the DPI issue, I hope :-) (Some other fixes in it as well)
[DeviceLens.zip](https://github.com/DelphiWorlds/DeviceLens/files/10608129/DeviceLens.zip)

**Comment by MyBuzzTechnologies** [comment]
That's awesome, thanks David!

**Comment by DelphiWorlds** [comment]
This is beta 3 of Device Lens 2 - it has saving to a file added, and also some exception handling to help track down the AV. Any exceptions will be logged to `Public Documents\DeviceLens\Logs`

[DeviceLens.zip](https://github.com/DelphiWorlds/DeviceLens/files/10717287/DeviceLens.zip)
