### ISSUE TITLE
TimeStamp resolution seems to be 1 min. only, in V2.0.1

### ISSUE THREAD

**Issue by Rollo62b** [DelphiWorlds/DeviceLens#17]
Hi Dave,

I'm just trying V2.0.1 and it seems that the timestamp is only 1 min., is that by design or can this be adjusted to milliseconds somewhere ?
![grafik](https://user-images.githubusercontent.com/4697968/234189858-3bfb1692-d40f-4068-a7aa-22e5e7363601.png)

**Comment by DelphiWorlds** [comment]
No, that is not intended. Can you let me know what make/model device you have, and what version of Android?

**Comment by DelphiWorlds** [comment]
[DeviceLens.zip](https://github.com/DelphiWorlds/DeviceLens/files/11327977/DeviceLens.zip)

Can you run the attached version of Device Lens (v2.0.2), and follow these steps:
1. Start logcat output
2. Right-click the grid, and check the `Logcat Debug` menu item
3. Wait a few seconds for some more output to appear
4. Right-click the grid, and uncheck the `Logcat Debug` menu item
5. Go to `Public Documents\DeviceLens\Logs`, and attach the `LogcatDebug.log` file to this issue

**Comment by Rollo62b** [comment]
[LogcatDebug.log](https://github.com/DelphiWorlds/DeviceLens/files/11330077/LogcatDebug.log)

The log seems to contain complete Timestamp info:

04-26 09:12:12.524  1889  2351 D ConnectivityService: NetReassign [no changes] [c 1] [a 0] [i 5]
04-26 09:12:12.699  2449  2449 D PowerNotificationWarningsGoogleImpl: onReceive: android.intent.action.BATTERY_CHANGED
04-26 09:12:12.702  2449  2449 D BatteryInfoBroadcast: onReceive: android.intent.action.BATTERY_CHANGED isPowerSaveMode: false
04-26 09:12:12.703 15676 15676 D DeviceStatisticsService: chargerType=1 batteryLevel=100 totalBatteryCapacity=4092000
04-26 09:12:12.703  2449  2449 D BatteryDefenderNotification: isPlugged: true | isOverheated: false | defenderEnabled: false | isCharged: true
04-26 09:12:12.707  2449  2449 I ReverseChargingControl: handleIntentForReverseCharging(): rtx=0 wlc=0 plgac=1 ac=1 acrtx=0 extra=1 this=com.google.android.systemui.reversecharging.ReverseChargingController@ea611a3
04-26 09:12:12.709  2449  9177 D PowerUI : can't show warning due to - plugged: true status unknown: false
04-26 09:12:15.536  1889  2351 D ConnectivityService: NetReassign [no changes] [c 0] [a 0] [i 2]
04-26 09:12:18.563  1889  2351 D ConnectivityService: NetReassign [no changes] [c 1] [a 0] [i 5]
04-26 09:12:19.624  1151  1199 D rlsservice: MonitorDisplayStatus client num 1, display status 1, sensor status 1
04-26 09:12:21.575  1889  2351 D ConnectivityService: NetReassign [no changes] [c 0] [a 0] [i 2]
04-26 09:12:24.602  1889  2351 D ConnectivityService: NetReassign [no changes] [c 1] [a 0] [i 4]
04-26 09:12:27.610  1889  2351 D ConnectivityService: NetReassign [no changes] [c 0] [a 0] [i 2]
04-26 09:12:30.638  1889  2351 D ConnectivityService: NetReassign [no changes] [c 0] [a 0] [i 5]
04-26 09:12:33.655  1889  2351 D ConnectivityService: NetReassign [no changes] [c 0] [a 0] [i 5]

**Comment by DelphiWorlds** [comment]
Thanks.. I'll check what the problem is

**Comment by DelphiWorlds** [comment]
It may be a regional setting issue - I just don't know which one at the moment. Can you test this code in Delphi on your machine?

```
uses
  System.DateUtils;

function TestParseDateTime(const AValue: string; out ADateTime: TDateTime): Boolean;
var
  LValueParts, LDateParts: TArray<string>;
  LDateSecond, LDateFirst, LDate: string;
  LDateSecondInt: Integer;
  LYear: TDateTime;
begin
  Result := False;
  LValueParts := AValue.Split([' ']);
  if Length(LValueParts) > 1 then
  begin
    LDateParts := LValueParts[0].Split(['-']);
    if Length(LDateParts) > 1 then
    begin
      LDateSecond := LDateParts[0];
      LDateFirst := LDateParts[1];
      if TryStrToInt(LDateSecond, LDateSecondInt) then
      begin
        LYear := Now;
        if LDateSecondInt > MonthOf(Now) then
          LYear := IncYear(Now, -1);
        LDate := LDateFirst + FormatSettings.DateSeparator + LDateSecond + FormatSettings.DateSeparator + YearOf(LYear).ToString;
        Result := TryStrToDateTime(LDate + ' ' + LValueParts[1], ADateTime);
      end;
    end;
  end;
end;

var
  LDateTime: TDateTime;
begin
  TestParseDateTime('04-26 09:12:12.524', LDateTime);
  ShowMessage('Value is: ' + FormatDateTime('yyyy.mm.dd hh:nn:ss.zzz', LDateTime));
end;
```

**Comment by DelphiWorlds** [comment]
[DeviceLens.zip](https://github.com/DelphiWorlds/DeviceLens/files/11337888/DeviceLens.zip)

I've changed the date/time parsing routine in the attached file (v2.0.2 again) so it should now work regardless of regional settings. Please let me know how it goes

**Comment by Rollo62b** [comment]
Sorry, I can only check now.
Yes, the new version V2.0.2 seems to work.
![grafik](https://user-images.githubusercontent.com/4697968/236248408-f5e9bec3-6a57-4619-b247-89986ae7c0be.png)

I also prepared a project for testing, according to your function above, to easily test on different Android devices.
Maybe that helps too, see enclosed project ZIP file.
[T473_DeviceLensFormat_001.zip](https://github.com/DelphiWorlds/DeviceLens/files/11398861/T473_DeviceLensFormat_001.zip)

When testing with the raw function from above, it still seems to set all seconds/milliseconds to "0".
I hope that helps still fro your conclusions:
![grafik](https://user-images.githubusercontent.com/4697968/236249439-07e427c6-a8ea-4a12-a434-6c283d1e3e02.png)

**Comment by DelphiWorlds** [comment]
> I also prepared a project for testing, according to your function above, to easily test on different Android devices.

That's great, but Device Lens is a Windows app. There's something possibly in the regional settings on your machine that was causing the issue.

**Comment by Rollo62b** [comment]
Yes, I thought the test app running on all platforms would be a good thing too.
You can compile that for windows too, but as you can see in the picture, it also shows the same conversion issue.

There is a button on the right side, to convert the current "Now", unfortunately it is hidden because the TEdit is too long.
Thinking further, I wanted to add several different methods, to extract and convert system times and formats.
