### ISSUE TITLE
Version 2.1.0 not starting ( Windows 10 ), probably AV crash

### ISSUE THREAD

**Issue by Rollo62b** [DelphiWorlds/DeviceLens#22]
Hi there,

I've tried out V2.1.0, but after instance and stated, it didn't appear and not even shows any message.
The EventLog looks like this:

> Fehlerbucket 1520854505958523302, Typ 4
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0
Problemsignatur:
P1: DeviceLens.exe
P2: 2.1.0.0
P3: 653045a3
P4: DeviceLens.exe
P5: 2.1.0.0
P6: 653045a3
P7: c0000005
P8: 000000000000e829
P9: 
P10: 

The former version runs perfectly.
The only special is a non-standard installation folder:
D:\Projects\_Tools\__Apps\DeviceLens\

Things I've tried:
- Uninstalled and reinstalled DeviceLens
- Windows 10 running in a Parallels VM (Intel)
- Updated PLS to latest version 19.1.0
- Updated VM's ParallelsTools
- Updated Windows 10 to latest version, cleaned up temporary files and reboot
- Started DeviceLens normally and as admin, it never appears in the TaskManager, directly crashes

I moved back to the last version, which works fine before and after all those measures.
Maybe that helps to find hidden issues.

**Comment by DelphiWorlds** [comment]
Sorry.. I missed deploying Skia with the executable. I'll re-issue a setup tomorrow (my time)

**Comment by DelphiWorlds** [comment]
I've updated the setup so that it now installs the required files
