### ISSUE TITLE
ADB command not found on selected SDK?

### ISSUE THREAD

**Issue by SARTrack** [DelphiWorlds/DeviceLens#23]
Using Delphi 12.

ADB command not found on selected SDK.
When I then select the directory of the used SDK, which contains the file adb.exe , it does not accept this.
As a result I cannot do anything at all.

What does it mean 'Selected SDK'... Selected where?
What does it mean 'ADB command': I do assume it is the 'adb.exe' file? 

Thanks, info@sartrack.nz

**Comment by DelphiWorlds** [comment]
> When I then select the directory of the used SDK, which contains the file adb.exe

What is the exact name of the folder you selected? It should be the **root* the of the Android SDK, i.e. the folder that contains the subfolders:

```
build-tools
cmdline-tools
platforms
```

etc

> What does it mean 'ADB command': I do assume it is the 'adb.exe' file?

Yes, it means 'adb.exe', which is in the `platform-tools` folder, but Device Lens requires you select the SDK **root** folder.

**Comment by SARTrack** [comment]
That worked, thanks. 
Please update the text in a next update, as it is totally unclear...

**Comment by birbilis** [comment]
the selector could verify that those subfolders exist and if not prompt the user to check for that when picking the folder

**Comment by DelphiWorlds** [comment]
> the selector could verify that those subfolders exist and if not prompt the user to check for that when picking the folder

The code already checks for that
