### ISSUE TITLE
v1.3.0, SDK Download/Install issue

### ISSUE THREAD

**Issue by MMSoft62** [DelphiWorlds/DeviceLens#8]
Unable to Download/Install SDKs

**Comment by DelphiWorlds** [comment]
There's insufficient information in this report to be able to do anything.

Have you installed a JDK?

**Comment by DelphiWorlds** [comment]
If you have Delphi installed with an Android SDK, you won't need to install another SDK. When Device Lens prompts you about an SDK, click No to allow you to select the location of the SDK

**Comment by MMSoft62** [comment]
thanks, work now.
(question how can I get the contents of the log display on the clipboard?)

**Comment by DelphiWorlds** [comment]
You can select lines of the output and press Ctrl-C to copy to the clipboard
