### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by kmarbach** [DelphiWorlds/DeviceLens#9]
I've used DeviceLens for a couple weeks and it is awesome. Thank you. Now I have a problem though. When I try to run it it shows up in task manager  under background processes, but the form never appears on my screen. How to fix that?

**Comment by DelphiWorlds** [comment]
I have no idea what might cause that. I may have to have you test a special build to try and diagnose the issue

**Comment by kmarbach** [comment]
This has happened again. The window never appears but devicelens.exe is in task manager. I am happy to test and give feedback.

**Comment by DelphiWorlds** [comment]
Can you try this version? http://freedelphicode.com/Downloads/DeviceLens-2.0.0-Beta.zip

**Comment by DelphiWorlds** [comment]
Resolved some issues with that beta: http://freedelphicode.com/Downloads/DeviceLens-2.0.0-Beta-2.zip
